"use strict";
var __cov_Uwxps2zlSgzTudDGapee4A = (Function('return this'))();
if (!__cov_Uwxps2zlSgzTudDGapee4A.$$cov_1411138070417$$) { __cov_Uwxps2zlSgzTudDGapee4A.$$cov_1411138070417$$ = {}; }
__cov_Uwxps2zlSgzTudDGapee4A = __cov_Uwxps2zlSgzTudDGapee4A.$$cov_1411138070417$$;
if (!(__cov_Uwxps2zlSgzTudDGapee4A['/home/nicolas/bird/angular-app-seed/src/app.js'])) {
   __cov_Uwxps2zlSgzTudDGapee4A['/home/nicolas/bird/angular-app-seed/src/app.js'] = {"path":"/home/nicolas/bird/angular-app-seed/src/app.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":8,"loc":{"start":{"line":8,"column":33},"end":{"line":8,"column":50}}},"2":{"name":"(anonymous_2)","line":11,"loc":{"start":{"line":11,"column":17},"end":{"line":11,"column":28}}},"3":{"name":"(anonymous_3)","line":14,"loc":{"start":{"line":14,"column":18},"end":{"line":14,"column":29}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":3,"column":33}},"2":{"start":{"line":4,"column":0},"end":{"line":4,"column":18}},"3":{"start":{"line":6,"column":0},"end":{"line":6,"column":46}},"4":{"start":{"line":8,"column":0},"end":{"line":17,"column":3}},"5":{"start":{"line":9,"column":2},"end":{"line":9,"column":25}},"6":{"start":{"line":10,"column":2},"end":{"line":10,"column":25}},"7":{"start":{"line":11,"column":2},"end":{"line":13,"column":4}},"8":{"start":{"line":12,"column":4},"end":{"line":12,"column":36}},"9":{"start":{"line":14,"column":2},"end":{"line":16,"column":4}},"10":{"start":{"line":15,"column":4},"end":{"line":15,"column":24}}},"branchMap":{}};
}
__cov_Uwxps2zlSgzTudDGapee4A = __cov_Uwxps2zlSgzTudDGapee4A['/home/nicolas/bird/angular-app-seed/src/app.js'];
__cov_Uwxps2zlSgzTudDGapee4A.s['1']++;var angular=require('angular');__cov_Uwxps2zlSgzTudDGapee4A.s['2']++;require('./ctrl');__cov_Uwxps2zlSgzTudDGapee4A.s['3']++;var app=angular.module('SeedApp',['ctrl']);__cov_Uwxps2zlSgzTudDGapee4A.s['4']++;app.controller('SeedController',function($scope){__cov_Uwxps2zlSgzTudDGapee4A.f['1']++;__cov_Uwxps2zlSgzTudDGapee4A.s['5']++;$scope.name='Johnny';__cov_Uwxps2zlSgzTudDGapee4A.s['6']++;$scope.banana='cake';__cov_Uwxps2zlSgzTudDGapee4A.s['7']++;$scope.sayHi=function(){__cov_Uwxps2zlSgzTudDGapee4A.f['2']++;__cov_Uwxps2zlSgzTudDGapee4A.s['8']++;$scope.hi='Hi '+$scope.name;};__cov_Uwxps2zlSgzTudDGapee4A.s['9']++;$scope.sayBye=function(){__cov_Uwxps2zlSgzTudDGapee4A.f['3']++;__cov_Uwxps2zlSgzTudDGapee4A.s['10']++;$scope.bye='Bye.';};});
