"use strict";
var __cov_rpsMxuGRWAMbdOJ7whrZJg = (Function('return this'))();
if (!__cov_rpsMxuGRWAMbdOJ7whrZJg.$$cov_1411138070417$$) { __cov_rpsMxuGRWAMbdOJ7whrZJg.$$cov_1411138070417$$ = {}; }
__cov_rpsMxuGRWAMbdOJ7whrZJg = __cov_rpsMxuGRWAMbdOJ7whrZJg.$$cov_1411138070417$$;
if (!(__cov_rpsMxuGRWAMbdOJ7whrZJg['/home/nicolas/bird/angular-app-seed/src/ctrl.js'])) {
   __cov_rpsMxuGRWAMbdOJ7whrZJg['/home/nicolas/bird/angular-app-seed/src/ctrl.js'] = {"path":"/home/nicolas/bird/angular-app-seed/src/ctrl.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":5,"loc":{"start":{"line":5,"column":74},"end":{"line":5,"column":91}}},"2":{"name":"(anonymous_2)","line":8,"loc":{"start":{"line":8,"column":17},"end":{"line":8,"column":28}}},"3":{"name":"(anonymous_3)","line":11,"loc":{"start":{"line":11,"column":18},"end":{"line":11,"column":29}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":3,"column":33}},"2":{"start":{"line":5,"column":0},"end":{"line":14,"column":3}},"3":{"start":{"line":6,"column":2},"end":{"line":6,"column":25}},"4":{"start":{"line":7,"column":2},"end":{"line":7,"column":25}},"5":{"start":{"line":8,"column":2},"end":{"line":10,"column":4}},"6":{"start":{"line":9,"column":4},"end":{"line":9,"column":36}},"7":{"start":{"line":11,"column":2},"end":{"line":13,"column":4}},"8":{"start":{"line":12,"column":4},"end":{"line":12,"column":24}}},"branchMap":{}};
}
__cov_rpsMxuGRWAMbdOJ7whrZJg = __cov_rpsMxuGRWAMbdOJ7whrZJg['/home/nicolas/bird/angular-app-seed/src/ctrl.js'];
__cov_rpsMxuGRWAMbdOJ7whrZJg.s['1']++;var angular=require('angular');__cov_rpsMxuGRWAMbdOJ7whrZJg.s['2']++;module.exports=angular.module('ctrl',[]).controller('SeedController2',function($scope){__cov_rpsMxuGRWAMbdOJ7whrZJg.f['1']++;__cov_rpsMxuGRWAMbdOJ7whrZJg.s['3']++;$scope.name='Johnny';__cov_rpsMxuGRWAMbdOJ7whrZJg.s['4']++;$scope.banana='cake';__cov_rpsMxuGRWAMbdOJ7whrZJg.s['5']++;$scope.sayHi=function(){__cov_rpsMxuGRWAMbdOJ7whrZJg.f['2']++;__cov_rpsMxuGRWAMbdOJ7whrZJg.s['6']++;$scope.hi='Hi '+$scope.name;};__cov_rpsMxuGRWAMbdOJ7whrZJg.s['7']++;$scope.sayBye=function(){__cov_rpsMxuGRWAMbdOJ7whrZJg.f['3']++;__cov_rpsMxuGRWAMbdOJ7whrZJg.s['8']++;$scope.bye='Bye.';};});
